set number relativenumber
"colorschem abstract
colorschem vim-monokai-tasty
syntax on
set autoindent
set smartindent
"set smarttab
"set noexpandtab
"set smartindent
"set shiftwidth=4
"set tabstop=4
set nowrap
set foldmethod=indent
set foldlevelstart=20
set nocompatible
set tabstop=8 
set softtabstop=0 
set expandtab 
set shiftwidth=4 
set smarttab
set clipboard=unnamedplus

" fix xterm Ctrl+arrow keys
if &term =~ '^screen'
    " tmux will send xterm-style keys when its xterm-keys option is on
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
endif

autocmd FileType python inoremap <c-Space> <Esc>/#++#<Enter>"_c4l

autocmd FileType python nnoremap <buffer> <F9> <Esc>:w<CR>:!clear;optirun python %<CR>
autocmd FileType python nnoremap <buffer> <F5> <Esc>:w<CR>:!clear;python %<CR>
autocmd FileType python inoremap ;( ()#++#<Esc>4hi
autocmd FileType python inoremap ;{ {}#++#<Esc>4hi
autocmd FileType python inoremap ;[ []#++#<Esc>4hi
autocmd FileType python inoremap ;" ""#++#<Esc>4hi
autocmd FileType python inoremap ;' ''#++#<Esc>4hi
autocmd FileType python noremap <c-c> I#<Esc>
autocmd FileType ruby noremap <c-c> I#<Esc>
autocmd FileType ruby nnoremap <buffer> <F5> <Esc>:w<CR>:!clear;ruby %<CR>
"autocmd FileType python vnoremap <c-c> I#<Esc>
nnoremap <space> za
vnoremap <space> zf

autocmd FileType tex set wrap
autocmd FileType tex nnoremap <Up> g<Up>
autocmd FileType tex nnoremap <Down> g<Down>
autocmd FileType tex nnoremap <buffer> <F5> <Esc>:w<CR>:!clear;pdflatex %<CR>
inoremap <S-Tab> <C-V><Tab>
autocmd FileType sh noremap <c-c> I#<Esc>
autocmd FileType sh nnoremap <buffer> <F5> <Esc>:w<CR>:!clear;bash %<CR>

execute pathogen#infect()
filetype plugin indent on
